Traceback (most recent call last):
  File "C:\Users\USUARIO\OneDrive\Documents\Book\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\USUARIO\OneDrive\Documents\Book\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USUARIO\OneDrive\Documents\Book\Lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USUARIO\OneDrive\Documents\Book\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\USUARIO\OneDrive\Documents\Book\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\USUARIO\OneDrive\Documents\Book\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\USUARIO\OneDrive\Documents\Book\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sympy import *
x, y, z = symbols('x y z')
x=int(input("Enter the value of x:"))
y=int(input("Enter the value of y:"))
z=x+y
print(z)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [1;32mIn[1], line 3[0m
[0;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01msympy[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m      2[0m x, y, z [38;5;241m=[39m symbols([38;5;124m'[39m[38;5;124mx y z[39m[38;5;124m'[39m)
[1;32m----> 3[0m x[38;5;241m=[39m[38;5;28mint[39m([38;5;28;43minput[39;49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mEnter the value of x:[39;49m[38;5;124;43m"[39;49m[43m)[49m)
[0;32m      4[0m y[38;5;241m=[39m[38;5;28mint[39m([38;5;28minput[39m([38;5;124m"[39m[38;5;124mEnter the value of y:[39m[38;5;124m"[39m))
[0;32m      5[0m z[38;5;241m=[39mx[38;5;241m+[39my

File [1;32m~\OneDrive\Documents\Book\Lib\site-packages\ipykernel\kernelbase.py:1201[0m, in [0;36mKernel.raw_input[1;34m(self, prompt)[0m
[0;32m   1199[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[0;32m   1200[0m     msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[1;32m-> 1201[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(msg)
[0;32m   1202[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[0;32m   1203[0m     [38;5;28mstr[39m(prompt),
[0;32m   1204[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[0;32m   1205[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[0;32m   1206[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[0;32m   1207[0m )

[1;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.

